# Generated by Django 3.2.5 on 2021-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=None, max_length=255, unique=True)),
                ('customer_id', models.IntegerField(blank=True, default=10)),
                ('fuel', models.CharField(blank=True, default='+', max_length=100, null=True)),
                ('veichel_segment', models.IntegerField(blank=True, default=10)),
                ('premium', models.FloatField(blank=True, null=True)),
                ('bodily_injury_liability', models.IntegerField(blank=True, default=10)),
                ('personal_injury_protection', models.IntegerField(blank=True, default=10)),
                ('property_damage_liability', models.IntegerField(blank=True, default=10)),
                ('collision', models.IntegerField(blank=True, default=10)),
                ('comprehensive', models.IntegerField(blank=True, default=10)),
                ('customer_gender', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_income_group', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_region', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_marital_status', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
