# Generated by Django 3.2.5 on 2021-07-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_insurance_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='fuel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='veichel_segment',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
